apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: python app that display time
  annotations:
    github.com/project-slug: pritiprogrammer/python-app
    backstage.io/techdocs-ref: dir:.
 
spec:
  type: service
  owner: development
  lifecycle: experimental
